<?php
declare(strict_types=1);
/** @var HolyMD\Content\ArticleDocument $article */ /** @var string $csrfToken */
$geoConfigured = (bool) (\HolyMD\Config\Env::get('HOLYMD_GEO_API_CREDENTIAL') && \HolyMD\Config\Env::get('HOLYMD_GEO_API_KEY') && \HolyMD\Config\Env::get('HOLYMD_GEO_API_ENDPOINT') && \HolyMD\Config\Env::get('HOLYMD_GEO_MODEL'));
$geoHost = (string) (parse_url((string) \HolyMD\Config\Env::get('HOLYMD_GEO_API_ENDPOINT'), PHP_URL_HOST) ?: '');
?>
<section class="geo-panel" data-geo-panel data-article-slug="<?= htmlspecialchars($article->slug, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?>">
<p class="eyebrow">GEO review</p><h2>Metadata proposals</h2><p class="muted">Analysis-only suggestions for metadata, entities, questions, links, hierarchy, sources, alt text, and structured data. Article prose is never generated or changed.</p><p class="muted">Provider: <?= $geoConfigured ? 'configured' : 'not configured' ?><?php if ($geoConfigured): ?> · <?= htmlspecialchars((string) \HolyMD\Config\Env::get('HOLYMD_GEO_MODEL'), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?> at <?= htmlspecialchars($geoHost, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?><?php endif; ?>. Credentials are never displayed.</p><button type="button" data-geo-review <?= $geoConfigured ? '' : 'disabled' ?>><span class="icon" aria-hidden="true">auto_awesome</span>Request GEO review</button><div data-geo-review-status aria-live="polite"></div><ol data-geo-proposals aria-label="GEO proposals"></ol><template data-geo-proposal-template><li><output data-geo-diff></output><button type="button" data-geo-accept><span class="icon" aria-hidden="true">check</span>Accept metadata</button><button type="button" data-geo-reject><span class="icon" aria-hidden="true">close</span>Reject</button><button type="button" data-geo-edit><span class="icon" aria-hidden="true">edit</span>Edit proposal</button></li></template><input type="hidden" data-geo-csrf value="<?= htmlspecialchars($csrfToken, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8') ?>">
</section>
