<?php
declare(strict_types=1);
/**
 * Shared footer, theme toggle script and document close.
 *
 * @var ?string $activeNav 'writing' | 'about' | null — index omits the Writing footer link.
 */
?>
  <footer class="site-footer"><div class="shell"><p><?= htmlspecialchars($siteName, ENT_QUOTES, 'UTF-8') ?> — writing by <?= htmlspecialchars($authorName, ENT_QUOTES, 'UTF-8') ?>. Powered by <a href="https://github.com/corlin/HolyMD" target="_blank" rel="noopener noreferrer">HolyMD</a>.</p><nav aria-label="Footer"><?php if ($activeNav !== 'writing'): ?><a href="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>/">Writing</a><?php endif; ?><?php foreach ($navPages ?? [] as $navPage): ?><a href="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>/<?= htmlspecialchars($navPage['slug'], ENT_QUOTES, 'UTF-8') ?>/"><?= htmlspecialchars($navPage['title'], ENT_QUOTES, 'UTF-8') ?></a><?php endforeach; ?><a href="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>/rss.xml">RSS</a><a href="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>/atom.xml">Atom</a><a href="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>/feed.json">JSON Feed</a><?php if ($generateLlmsTxt): ?><a href="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>/llms.txt">llms.txt</a><a href="<?= htmlspecialchars($basePath, ENT_QUOTES, 'UTF-8') ?>/llms-full.txt">llms-full.txt</a><?php endif; ?></nav></div></footer>
  <script>!function(){var e={auto:{label:"System",next:"light",icon:"brightness_auto"},light:{label:"Light",next:"dark",icon:"light_mode"},dark:{label:"Dark",next:"auto",icon:"dark_mode"}},t=function(){var t=localStorage.getItem("holymd_theme");return"light"===t||"dark"===t?t:"auto"},a=function(t){"auto"===t?(localStorage.removeItem("holymd_theme"),document.documentElement.removeAttribute("data-theme")):(localStorage.setItem("holymd_theme",t),document.documentElement.setAttribute("data-theme",t)),document.querySelectorAll("[data-theme-set]").forEach(function(e){var a=e.getAttribute("data-theme-set")===t;e.classList.toggle("active",a),e.setAttribute("aria-pressed",a?"true":"false")});var a=document.querySelector("[data-theme-cycle]");if(a){var l=e[t],n=e[l.next];a.setAttribute("aria-label","Theme: "+l.label+". Activate to use "+n.label+" theme."),a.querySelector(".icon").textContent=l.icon}};a(t()),document.addEventListener("click",function(l){var n=l.target.closest("[data-theme-set]");if(n)return void a(n.getAttribute("data-theme-set"));var r=l.target.closest("[data-theme-cycle]");r&&a(e[t()].next)})}();</script>
<?php if (!empty($showReadingProgress)): ?>
  <script>!function(){var e=document.querySelector(".header-reading-progress"),t=document.querySelector("#article-content");if(!e||!t)return;var r=e.querySelector(".progress-fill"),a=e.querySelector(".progress-value"),n=function(){var n=t.getBoundingClientRect(),i=n.height-innerHeight,o=0;if(n.bottom<=innerHeight||innerHeight+window.pageYOffset>=document.documentElement.scrollHeight-5){o=1}else if(i>0&&n.top<0){o=Math.min(1,Math.max(0,-n.top/i))}else if(n.top<=0){o=1}var s=Math.round(100*o);r.style.transform="scaleX("+o+")",a.textContent=s+"%",e.setAttribute("aria-valuenow",String(s))};addEventListener("scroll",n,{passive:!0}),addEventListener("resize",n),n();var i=Array.from(document.querySelectorAll(".toc-rail a")),o=Array.from(t.querySelectorAll("h2[id],h3[id],h4[id]"));if(i.length&&o.length&&"IntersectionObserver"in window){var s=function(e){i.forEach(function(t){t.removeAttribute("aria-current")});var r=i.find(function(t){return t.getAttribute("href")==="#"+e});r&&r.setAttribute("aria-current","location")},c=new IntersectionObserver(function(e){var t=e.filter(function(e){return e.isIntersecting}).sort(function(e,t){return e.boundingClientRect.top-t.boundingClientRect.top});t[0]&&s(t[0].target.id)},{rootMargin:"-18% 0px -70% 0px"});s(o[0].id),o.forEach(function(e){c.observe(e)})}}();</script>
<?php endif; ?>
  <script>!function(){var e=Array.from(document.querySelectorAll("#article-content img")),t=document.querySelector(".image-viewer");if(!e.length||!t)return;var r=t.querySelector(".image-viewer-canvas img"),a=t.querySelector(".image-viewer-caption"),n=t.querySelector(".image-viewer-count"),i=t.querySelector(".image-viewer-scale"),o=t.querySelector(".image-viewer-download"),s=t.querySelector('[data-image-nav="prev"]'),c=t.querySelector('[data-image-nav="next"]'),l=0,d=1,u=null,m=function(){var m=e[l],g=m.getAttribute("alt")||"Image";r.src=m.currentSrc||m.src,r.alt=g,a.textContent=g,n.textContent=e.length>1?l+1+" of "+e.length:"",o.href=r.src,s.hidden=c.hidden=e.length<2,p(1),u=m},p=function(e){d=Math.min(4,Math.max(.5,e)),r.style.transform="scale("+d+")",i.textContent=Math.round(100*d)+"%"},g=function(t){l=(l+t+e.length)%e.length,m()};e.forEach(function(r,a){r.tabIndex=0,r.setAttribute("role","button"),r.setAttribute("aria-haspopup","dialog"),r.setAttribute("aria-label",(r.getAttribute("alt")||"Image")+" — open full-size preview"),r.addEventListener("click",function(){l=a,m(),t.showModal()}),r.addEventListener("keydown",function(e){("Enter"===e.key||" "===e.key)&&(e.preventDefault(),r.click())})}),t.addEventListener("click",function(e){if(e.target===t)t.close();var r=e.target.closest("[data-image-close],[data-image-zoom],[data-image-nav]");if(!r)return;r.hasAttribute("data-image-close")?t.close():r.hasAttribute("data-image-nav")?g("next"===r.dataset.imageNav?1:-1):p("in"===r.dataset.imageZoom?d+.25:"out"===r.dataset.imageZoom?d-.25:1)}),t.addEventListener("keydown",function(e){"ArrowRight"===e.key?g(1):"ArrowLeft"===e.key?g(-1):("+"===e.key||"="===e.key)?p(d+.25):"-"===e.key?p(d-.25):"0"===e.key&&p(1)}),t.addEventListener("close",function(){r.src="",u&&u.focus()})}();</script>
<?php if (!empty($assetSearch)): ?>
  <script src="<?= htmlspecialchars($assetSearch, ENT_QUOTES, 'UTF-8') ?>" defer></script>
<?php endif; ?>
</body>
</html>
