<!doctype html>
<html lang="<?= htmlspecialchars($siteLanguage, ENT_QUOTES, 'UTF-8') ?>">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?= htmlspecialchars($article->title) ?> | <?= htmlspecialchars($siteName) ?></title><meta name="description" content="<?= htmlspecialchars($summary) ?>">
  <meta property="og:type" content="article"><meta property="og:title" content="<?= htmlspecialchars($article->title) ?>"><meta property="og:description" content="<?= htmlspecialchars($summary) ?>"><meta property="og:url" content="<?= htmlspecialchars($url) ?>"><meta property="og:site_name" content="<?= htmlspecialchars($siteName) ?>">
  <meta name="twitter:card" content="summary"><meta name="twitter:title" content="<?= htmlspecialchars($article->title) ?>"><meta name="twitter:description" content="<?= htmlspecialchars($summary) ?>"><link rel="canonical" href="<?= htmlspecialchars($url) ?>"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json"><?= $jsonLd ?></script>
</head>
<body>
  <a class="skip-link" href="#article-content">Skip to article</a>
  <header class="site-header"><div class="shell nav-row"><a class="wordmark" href="/" aria-label="<?= htmlspecialchars($siteName) ?> home"><?= htmlspecialchars($siteName) ?></a><nav aria-label="Primary"><a href="/">Writing</a><a href="/about/">About</a><a href="/rss.xml">RSS</a></nav></div></header>
  <main><article><div class="article-page shell"><header class="article-header"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Writing</a><span aria-hidden="true">/</span><span aria-current="page"><?= htmlspecialchars($article->title) ?></span></nav><?php if ($topics !== []): ?><p class="eyebrow"><?php foreach ($topics as $index => $topic): ?><?php if ($index > 0): ?><span aria-hidden="true"> · </span><?php endif; ?><a href="/topics/<?= htmlspecialchars(trim((string) preg_replace('/-+/', '-', preg_replace('/[^a-z0-9]+/', '-', strtolower($topic)) ?? ''), '-')) ?>/"><?= htmlspecialchars($topic) ?></a><?php endforeach; ?></p><?php endif; ?><h1><?= htmlspecialchars($article->title) ?></h1><?php if ($summary !== ''): ?><p class="deck"><?= htmlspecialchars($summary) ?></p><?php endif; ?><dl class="reading-meta"><div><dt>Written by</dt><dd rel="author"><?= htmlspecialchars($authorName) ?></dd></div><div><dt>Published</dt><dd><time datetime="<?= htmlspecialchars($date) ?>"><?= htmlspecialchars($date) ?></time></dd></div><?php if ($modified !== $date): ?><div><dt>Updated</dt><dd><time datetime="<?= htmlspecialchars($modified) ?>"><?= htmlspecialchars($modified) ?></time></dd></div><?php endif; ?></dl></header>
    <div id="article-content" class="prose"><?= $contentHtml ?></div>
    <?php if ($sources !== []): ?><section aria-labelledby="sources-heading"><div class="article-section sources"><h2 id="sources-heading">Sources</h2><ol><?php foreach ($sources as $source): ?><li><a href="<?= htmlspecialchars($source) ?>" rel="cite noopener noreferrer"><?= htmlspecialchars($source) ?></a></li><?php endforeach; ?></ol></div></section><?php endif; ?>
    <aside class="author-box" aria-labelledby="author-heading"><p class="eyebrow">About the author</p><h2 id="author-heading"><?= htmlspecialchars($authorName) ?></h2><p><?= htmlspecialchars($siteName) ?> is a personal publication.</p><a class="text-link" href="/about/">Read more about <?= htmlspecialchars($authorName) ?> <span aria-hidden="true">→</span></a></aside>
    <?php if ($related !== []): ?><section class="article-section related" aria-labelledby="related-heading"><p class="eyebrow">Continue reading</p><h2 id="related-heading">Related articles</h2><div class="article-list"><?php foreach ($related as $relatedArticle): ?><article class="article-row"><div><h3><a href="/articles/<?= htmlspecialchars($relatedArticle->slug) ?>/"><?= htmlspecialchars($relatedArticle->title) ?></a></h3><?php $relatedSummary = (string) $relatedArticle->frontMatter->get('summary', ''); if ($relatedSummary !== ''): ?><p><?= htmlspecialchars($relatedSummary) ?></p><?php endif; ?></div><a class="quiet-arrow" href="/articles/<?= htmlspecialchars($relatedArticle->slug) ?>/" aria-label="Read <?= htmlspecialchars($relatedArticle->title) ?>">→</a></article><?php endforeach; ?></div></section><?php endif; ?>
  </div></article></main>
  <footer class="site-footer"><div class="shell"><p><?= htmlspecialchars($siteName) ?> — writing by <?= htmlspecialchars($authorName) ?>.</p><nav aria-label="Footer"><a href="/">Writing</a><a href="/about/">About</a><a href="/rss.xml">RSS</a></nav></div></footer>
</body>
</html>
